controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
# app_get_total_sum:
#   path: 'cart/get-total-sum'
#   controller: 'App\Controller\CartControllerClass::getTotalSum'
